name: Generate snake animation

on:
  schedule:
    # Se ejecuta cada 12 horas
    - cron: "0 */12 * * *"
  
  # Permite ejecutar manualmente
  workflow_dispatch:
  
  # Se ejecuta en push a main
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Genera el archivo SVG de la serpiente
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jhoncastro28
          outputs: dist/snake.svg?palette=github-dark

      # Sube el archivo generado al repositorio
      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
